import { PrizeItem } from '@/types/wheel';

export const DEFAULT_PRIZES: PrizeItem[] = [
  {
    id: 'prize-1',
    line1: 'iPhone 16',
    line2: 'Pro Max',
    name: 'iPhone 16 Pro Max',
    color: '#FF6B00',
    icon: 'smartphone',
    weight: 1,
  },
  {
    id: 'prize-2',
    line1: 'MacBook',
    line2: 'Pro M3',
    name: 'MacBook Pro M3',
    color: '#1E293B',
    icon: 'laptop',
    weight: 1,
  },
  {
    id: 'prize-3',
    line1: 'iPad Pro',
    line2: 'M4',
    name: 'iPad Pro M4',
    color: '#0EA5E9',
    icon: 'tablet',
    weight: 1,
  },
  {
    id: 'prize-4',
    line1: 'Apple Watch',
    line2: 'Ultra 2',
    name: 'Apple Watch Ultra 2',
    color: '#10B981',
    icon: 'watch',
    weight: 1,
  },
  {
    id: 'prize-5',
    line1: 'Tai nghe',
    line2: 'AirPods Max',
    name: 'AirPods Max',
    color: '#8B5CF6',
    icon: 'headphones',
    weight: 1,
  },
  {
    id: 'prize-6',
    line1: 'Máy chơi game',
    line2: 'PS5',
    name: 'PlayStation 5',
    color: '#F59E0B',
    icon: 'gamepad',
    weight: 1,
  },
  {
    id: 'prize-7',
    line1: 'Loa Bluetooth',
    line2: 'Marshall',
    name: 'Loa Marshall',
    color: '#EF4444',
    icon: 'speaker',
    weight: 1,
  },
  {
    id: 'prize-8',
    line1: 'Bàn Phím Cơ',
    line2: 'Custom',
    name: 'Bàn Phím Cơ Custom',
    color: '#059669',
    icon: 'keyboard',
    weight: 1,
  },
  {
    id: 'prize-9',
    line1: 'Chuột Gaming',
    line2: 'MX Master 3S',
    name: 'Chuột MX Master 3S',
    color: '#6366F1',
    icon: 'mouse',
    weight: 1,
  },
  {
    id: 'prize-10',
    line1: 'Củ Sạc Nhanh',
    line2: 'Anker 140W',
    name: 'Củ Sạc Anker 140W',
    color: '#D946EF',
    icon: 'charger',
    weight: 1,
  },
];
