import React from 'react';
import {
  Smartphone,
  Laptop,
  Tablet,
  Watch,
  Headphones,
  Gamepad2,
  Speaker,
  Keyboard,
  Mouse,
  Zap,
  Camera,
  Tv,
  Monitor,
  Cpu,
  HardDrive,
  Wifi,
  Mic,
  BatteryCharging,
  Gift,
  Star,
  Trophy,
  Crown,
  Medal,
  Gem,
  Ticket,
  Sparkles,
  Coins,
  Wallet,
  ShoppingBag,
  Percent,
  Award,
  Car,
  Bike,
  Plane,
  Coffee,
  Pizza,
  Utensils,
  Shirt,
  Glasses,
  Heart,
  Flame,
  Music,
  ShieldCheck,
  Sun,
  Package,
} from 'lucide-react';
import { PrizeIconKey } from '@/types/wheel';

export interface IconMeta {
  key: PrizeIconKey;
  label: string;
  category: 'tech' | 'reward' | 'lifestyle';
}

export const ICON_METADATA: IconMeta[] = [
  // 1. Công nghệ (Tech)
  { key: 'smartphone', label: 'Điện thoại', category: 'tech' },
  { key: 'laptop', label: 'Laptop / MacBook', category: 'tech' },
  { key: 'tablet', label: 'Máy tính bảng / iPad', category: 'tech' },
  { key: 'watch', label: 'Đồng hồ thông minh', category: 'tech' },
  { key: 'headphones', label: 'Tai nghe AirPods', category: 'tech' },
  { key: 'gamepad', label: 'Tay cầm chơi game', category: 'tech' },
  { key: 'speaker', label: 'Loa Bluetooth', category: 'tech' },
  { key: 'keyboard', label: 'Bàn phím cơ', category: 'tech' },
  { key: 'mouse', label: 'Chuột Gaming', category: 'tech' },
  { key: 'charger', label: 'Củ sạc siêu tốc', category: 'tech' },
  { key: 'camera', label: 'Máy ảnh kỹ thuật số', category: 'tech' },
  { key: 'tv', label: 'Smart TV', category: 'tech' },
  { key: 'monitor', label: 'Màn hình máy tính', category: 'tech' },
  { key: 'cpu', label: 'Chip vi xử lý / GPU', category: 'tech' },
  { key: 'hard-drive', label: 'Ổ cứng di động', category: 'tech' },
  { key: 'wifi', label: 'Bộ phát Wifi Router', category: 'tech' },
  { key: 'mic', label: 'Microphone thu âm', category: 'tech' },
  { key: 'battery', label: 'Pin dự phòng', category: 'tech' },

  // 2. Giải thưởng & May mắn (Reward)
  { key: 'gift', label: 'Hộp quà may mắn', category: 'reward' },
  { key: 'star', label: 'Ngôi sao may mắn', category: 'reward' },
  { key: 'trophy', label: 'Cúp vàng vô địch', category: 'reward' },
  { key: 'crown', label: 'Vương miện hoàng gia', category: 'reward' },
  { key: 'medal', label: 'Huy chương vàng', category: 'reward' },
  { key: 'gem', label: 'Kim cương quý giá', category: 'reward' },
  { key: 'ticket', label: 'Vé trúng thưởng', category: 'reward' },
  { key: 'sparkles', label: 'Phép màu may mắn', category: 'reward' },
  { key: 'coins', label: 'Tiền xu tài lộc', category: 'reward' },
  { key: 'wallet', label: 'Ví tiền mặt', category: 'reward' },
  { key: 'shopping-bag', label: 'Túi mua sắm', category: 'reward' },
  { key: 'percent', label: 'Voucher giảm giá', category: 'reward' },
  { key: 'award', label: 'Bằng khen / Giải thưởng', category: 'reward' },

  // 3. Đời sống & Xe cộ (Lifestyle)
  { key: 'car', label: 'Xe ô tô sang', category: 'lifestyle' },
  { key: 'bike', label: 'Xe máy / Xe đạp', category: 'lifestyle' },
  { key: 'plane', label: 'Vé máy bay du lịch', category: 'lifestyle' },
  { key: 'coffee', label: 'Cà phê cao cấp', category: 'lifestyle' },
  { key: 'pizza', label: 'Bữa tiệc ẩm thực', category: 'lifestyle' },
  { key: 'utensils', label: 'Bữa tối sang trọng', category: 'lifestyle' },
  { key: 'shirt', label: 'Thời trang hàng hiệu', category: 'lifestyle' },
  { key: 'glasses', label: 'Kính mát sành điệu', category: 'lifestyle' },
  { key: 'heart', label: 'Trái tim sức khỏe', category: 'lifestyle' },
  { key: 'flame', label: 'Ngọn lửa nhiệt huyết', category: 'lifestyle' },
  { key: 'zap', label: 'Tia chớp tốc độ', category: 'lifestyle' },
  { key: 'music', label: 'Vé ca nhạc / Nhạc cụ', category: 'lifestyle' },
  { key: 'shield-check', label: 'Gói bảo hành VIP', category: 'lifestyle' },
  { key: 'sun', label: 'Kỳ nghỉ mùa hè', category: 'lifestyle' },
  { key: 'package', label: 'Gói bưu phẩm đặc biệt', category: 'lifestyle' },
];

export const AVAILABLE_ICONS: PrizeIconKey[] = ICON_METADATA.map((m) => m.key);

export const TECH_ICONS: Record<PrizeIconKey, React.ReactNode> = {
  // Tech
  smartphone: <Smartphone size={22} strokeWidth={2.2} />,
  laptop: <Laptop size={22} strokeWidth={2.2} />,
  tablet: <Tablet size={22} strokeWidth={2.2} />,
  watch: <Watch size={22} strokeWidth={2.2} />,
  headphones: <Headphones size={22} strokeWidth={2.2} />,
  gamepad: <Gamepad2 size={22} strokeWidth={2.2} />,
  speaker: <Speaker size={22} strokeWidth={2.2} />,
  keyboard: <Keyboard size={22} strokeWidth={2.2} />,
  mouse: <Mouse size={22} strokeWidth={2.2} />,
  charger: <Zap size={22} strokeWidth={2.2} />,
  camera: <Camera size={22} strokeWidth={2.2} />,
  tv: <Tv size={22} strokeWidth={2.2} />,
  monitor: <Monitor size={22} strokeWidth={2.2} />,
  cpu: <Cpu size={22} strokeWidth={2.2} />,
  'hard-drive': <HardDrive size={22} strokeWidth={2.2} />,
  wifi: <Wifi size={22} strokeWidth={2.2} />,
  mic: <Mic size={22} strokeWidth={2.2} />,
  battery: <BatteryCharging size={22} strokeWidth={2.2} />,

  // Rewards
  gift: <Gift size={22} strokeWidth={2.2} />,
  star: <Star size={22} strokeWidth={2.2} />,
  trophy: <Trophy size={22} strokeWidth={2.2} />,
  crown: <Crown size={22} strokeWidth={2.2} />,
  medal: <Medal size={22} strokeWidth={2.2} />,
  gem: <Gem size={22} strokeWidth={2.2} />,
  ticket: <Ticket size={22} strokeWidth={2.2} />,
  sparkles: <Sparkles size={22} strokeWidth={2.2} />,
  coins: <Coins size={22} strokeWidth={2.2} />,
  wallet: <Wallet size={22} strokeWidth={2.2} />,
  'shopping-bag': <ShoppingBag size={22} strokeWidth={2.2} />,
  percent: <Percent size={22} strokeWidth={2.2} />,
  award: <Award size={22} strokeWidth={2.2} />,

  // Lifestyle
  car: <Car size={22} strokeWidth={2.2} />,
  bike: <Bike size={22} strokeWidth={2.2} />,
  plane: <Plane size={22} strokeWidth={2.2} />,
  coffee: <Coffee size={22} strokeWidth={2.2} />,
  pizza: <Pizza size={22} strokeWidth={2.2} />,
  utensils: <Utensils size={22} strokeWidth={2.2} />,
  shirt: <Shirt size={22} strokeWidth={2.2} />,
  glasses: <Glasses size={22} strokeWidth={2.2} />,
  heart: <Heart size={22} strokeWidth={2.2} />,
  flame: <Flame size={22} strokeWidth={2.2} />,
  zap: <Zap size={22} strokeWidth={2.2} />,
  music: <Music size={22} strokeWidth={2.2} />,
  'shield-check': <ShieldCheck size={22} strokeWidth={2.2} />,
  sun: <Sun size={22} strokeWidth={2.2} />,
  package: <Package size={22} strokeWidth={2.2} />,
};
